-- Supabase PostgreSQL Schema for Calories AI System

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Meals Table
CREATE TABLE IF NOT EXISTS public.meals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    raw_input TEXT NOT NULL,
    input_type TEXT DEFAULT 'text',
    notes TEXT
);

-- 2. Meal Items Table
CREATE TABLE IF NOT EXISTS public.meal_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_id BIGINT REFERENCES public.meals(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    category TEXT DEFAULT 'general',
    quantity_g NUMERIC NOT NULL,
    calories NUMERIC NOT NULL,
    protein_g NUMERIC NOT NULL,
    fat_g NUMERIC NOT NULL,
    carbs_g NUMERIC NOT NULL
);

-- 3. Product Prices Table
CREATE TABLE IF NOT EXISTS public.product_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT UNIQUE NOT NULL,
    category TEXT DEFAULT 'general',
    price_rub NUMERIC NOT NULL,
    weight_g NUMERIC NOT NULL,
    protein_per_100g NUMERIC DEFAULT 0,
    fat_per_100g NUMERIC DEFAULT 0,
    carbs_per_100g NUMERIC DEFAULT 0,
    calories_per_100g NUMERIC DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Coach Recommendations Table
CREATE TABLE IF NOT EXISTS public.coach_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    topic TEXT NOT NULL,
    recommendation TEXT NOT NULL,
    severity TEXT DEFAULT 'info'
);

-- 5. User Goals Table
CREATE TABLE IF NOT EXISTS public.user_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calories NUMERIC DEFAULT 2200,
    protein_g NUMERIC DEFAULT 160,
    fat_g NUMERIC DEFAULT 70,
    carbs_g NUMERIC DEFAULT 230
);

-- Row Level Security (RLS) Policies (Enable public access for API Key usage)
ALTER TABLE public.meals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meal_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_goals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon read/write meals" ON public.meals FOR ALL USING (true);
CREATE POLICY "Allow anon read/write meal_items" ON public.meal_items FOR ALL USING (true);
CREATE POLICY "Allow anon read/write product_prices" ON public.product_prices FOR ALL USING (true);
CREATE POLICY "Allow anon read/write coach_recommendations" ON public.coach_recommendations FOR ALL USING (true);
CREATE POLICY "Allow anon read/write user_goals" ON public.user_goals FOR ALL USING (true);
